CREATE TABLE subscription
(
    id          BIGSERIAL NOT NULL,
    author_id   BIGINT DEFAULT NULL,
    follower_id BIGINT DEFAULT NULL,
    created_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_A3C664D3F675F31B ON subscription (author_id);
CREATE INDEX IDX_A3C664D3AC24F853 ON subscription (follower_id);
CREATE UNIQUE INDEX UNIQ_A3C664D3F675F31BAC24F853 ON subscription (author_id, follower_id);

ALTER TABLE subscription
    ADD CONSTRAINT FK_A3C664D3F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE subscription
    ADD CONSTRAINT FK_A3C664D3AC24F853 FOREIGN KEY (follower_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
