CREATE TABLE tweet
(
    id         BIGSERIAL    NOT NULL,
    author_id  BIGINT DEFAULT NULL,
    text       VARCHAR(140) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_3D660A3BF675F31B ON tweet (author_id);

CREATE TABLE "user"
(
    id         BIGSERIAL   NOT NULL,
    login      VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE tweet
    ADD CONSTRAINT FK_3D660A3BF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
